/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LOUSER_PB_H_INCLUDED
#define PB_LOUSER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(32) LoUserUser_salt_t;
typedef PB_BYTES_ARRAY_T(32) LoUserUser_password_hash_t;
/* * One louser user. `id` is assigned on insert; `salt` is a 32B per-user value. */
typedef struct _LoUserUser {
    uint64_t id;
    char username[33];
    LoUserUser_salt_t salt;
    LoUserUser_password_hash_t password_hash;
    bool admin;
    uint32_t created_ms;
} LoUserUser;

typedef PB_BYTES_ARRAY_T(96) LoUserSession_bind_fp_t;
/* * Active session keyed by `lostar::NodeId` (!xxxxxxxx low bits). `bind_fp` is the caller's
  NodeRef.ctx captured at login; empty on platforms whose id already equals native identity. */
typedef struct _LoUserSession {
    uint32_t node_id;
    uint64_t user_id;
    LoUserSession_bind_fp_t bind_fp;
    uint32_t created_ms;
} LoUserSession;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LoUserUser_init_default                  {0, "", {0, {0}}, {0, {0}}, 0, 0}
#define LoUserSession_init_default               {0, 0, {0, {0}}, 0}
#define LoUserUser_init_zero                     {0, "", {0, {0}}, {0, {0}}, 0, 0}
#define LoUserSession_init_zero                  {0, 0, {0, {0}}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define LoUserUser_id_tag                        1
#define LoUserUser_username_tag                  2
#define LoUserUser_salt_tag                      3
#define LoUserUser_password_hash_tag             4
#define LoUserUser_admin_tag                     5
#define LoUserUser_created_ms_tag                6
#define LoUserSession_node_id_tag                1
#define LoUserSession_user_id_tag                2
#define LoUserSession_bind_fp_tag                3
#define LoUserSession_created_ms_tag             4

/* Struct field encoding specification for nanopb */
#define LoUserUser_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   username,          2) \
X(a, STATIC,   SINGULAR, BYTES,    salt,              3) \
X(a, STATIC,   SINGULAR, BYTES,    password_hash,     4) \
X(a, STATIC,   SINGULAR, BOOL,     admin,             5) \
X(a, STATIC,   SINGULAR, UINT32,   created_ms,        6)
#define LoUserUser_CALLBACK NULL
#define LoUserUser_DEFAULT NULL

#define LoUserSession_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   node_id,           1) \
X(a, STATIC,   SINGULAR, UINT64,   user_id,           2) \
X(a, STATIC,   SINGULAR, BYTES,    bind_fp,           3) \
X(a, STATIC,   SINGULAR, UINT32,   created_ms,        4)
#define LoUserSession_CALLBACK NULL
#define LoUserSession_DEFAULT NULL

extern const pb_msgdesc_t LoUserUser_msg;
extern const pb_msgdesc_t LoUserSession_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LoUserUser_fields &LoUserUser_msg
#define LoUserSession_fields &LoUserSession_msg

/* Maximum encoded size of messages (where known) */
#define LOUSER_PB_H_MAX_SIZE                     LoUserUser_size
#define LoUserSession_size                       121
#define LoUserUser_size                          121

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
